### ISSUE TITLE
无法适配到devenv.exe的问题

### ISSUE THREAD

**Issue by pedoc** [lspcieee/lspcieee_ahk#2]
使用合格ahk我发现在我机器上无法在vs13中生效，但是在notepad++等程序是ok的。检查进程发现有devenv.exe，并且再启动时能够弹出“自动切换到英文对话框”但是一旦打开解决方案之后，就无效了。然后在本机的vs15上测试发现也是有效的，无解

**Comment by lspcieee** [comment]
可以试试将ahk脚本以管理员身份运行试试。
参考这段代码：

if not A_IsAdmin
{
   Run *RunAs "%A_ScriptFullPath%"  ; Requires v1.0.92.01+
   ExitApp
}

https://github.com/lspcieee/lspcieee_ahk/blob/master/AutoHotKey.ahk
