### ISSUE TITLE
在vim中自动更改输入法失效

### ISSUE THREAD

**Issue by jiacj** [lspcieee/lspcieee_ahk#3]
把vim放在英文输入法组，激活gvim时有时有效有时无效

**Comment by lspcieee** [comment]
请确认默认输入法设置是不是和ahk的默认设置一样，否则请改一下代码试试：
AHK切换中文输入法发送快捷键为Control+,（搜狗输入法默认设置）切换英文输入法发送快捷键为Ctrl+Space
