### ISSUE TITLE
jetbrain的ide在敲注释时无法自动切换中文

### ISSUE THREAD

**Issue by Cey1anze** [lspcieee/lspcieee_ahk#5]
ahk的分组配置和编辑器分组都加了ide，打开ide的时候可以切换输入法，但是写注释的时候就无法自动切换中文

**Comment by lspcieee** [comment]
写注释，目前代码仅仅对自己常用的Visual Studio 做了适配，其余的IDE众多，可能辛苦你自己适配一下。
